<?php

namespace Webkul\TorobPay\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Webkul\Checkout\Facades\Cart;
use Webkul\Sales\Repositories\InvoiceRepository;
use Webkul\Sales\Repositories\OrderRepository;
use Webkul\Sales\Transformers\OrderResource;
use Webkul\TorobPay\Repositories\TorobPayRepository;
use Webkul\TorobPay\Services\TorobPayService;

class TorobPayController extends Controller
{
    public function __construct(
        protected TorobPayService $torobPayService,
        protected OrderRepository $orderRepository,
        protected InvoiceRepository $invoiceRepository,
        protected TorobPayRepository $torobPayRepository
    ) {
    }

    /**
     * Start TorobPay payment.
     */
    public function redirect()
    {
        try {
            $cart = Cart::getCart();

            if (! $cart) {
                return $this->checkoutError(
                    'سبد خرید پیدا نشد.'
                );
            }

            if (! $cart->items || $cart->items->isEmpty()) {
                return $this->checkoutError(
                    'سبد خرید خالی است.'
                );
            }

            $shippingAddress = $cart->shipping_address;

            if (! $shippingAddress) {
                return $this->checkoutError(
                    'اطلاعات آدرس ارسال کامل نیست.'
                );
            }

            $currency = strtoupper(
                (string) (
                    core()->getConfigData(
                        'sales.payment_methods.torobpay.currency'
                    ) ?: 'T'
                )
            );

            /*
             * TorobPay expects all monetary values in Rial.
             */
            $amount = $this->toRial(
                (float) $cart->base_grand_total,
                $currency
            );

            if ($amount < 200000) {
                return $this->checkoutError(
                    'مبلغ سفارش برای پرداخت اعتباری ترب‌پی کمتر از حد مجاز است.'
                );
            }

            if ($amount > 1000000000) {
                return $this->checkoutError(
                    'مبلغ سفارش برای پرداخت اعتباری ترب‌پی بیشتر از حد مجاز است.'
                );
            }

            /*
             * transactionId is generated by the merchant.
             */
            $transactionId = (string) Str::uuid();

            /*
             * Build cart items according to TorobPay documentation.
             */
            $cartItems = [];

            foreach ($cart->items as $item) {
                $product = $item->product;

                $cartItems[] = [
                    'id' => (string) $item->product_id,

                    'name' => (string) (
                        $item->name
                        ?? $product?->name
                        ?? 'محصول'
                    ),

                    'count' => (int) $item->quantity,

                    /*
                     * Amount of this cart item in Rial.
                     */
                    'amount' => $this->toRial(
                        (float) $item->base_total,
                        $currency
                    ),

                    'category' => 'general',
                ];
            }

            $shippingAmount = $this->toRial(
                (float) ($cart->base_shipping_amount ?? 0),
                $currency
            );

            $taxAmount = $this->toRial(
                (float) ($cart->base_tax_total ?? 0),
                $currency
            );

            $cartList = [
                [
                    'cartId' => (string) $cart->id,
                    
                    'totalAmount' => $amount,

                    'taxAmount' => $taxAmount,

                    'shippingAmount' => $shippingAmount,

                    'isTaxIncluded' => false,

                    'isShipmentIncluded' => $shippingAmount > 0,

                    'cartItems' => $cartItems,
                ],
            ];

            /*
             * Required checkout customer/address fields.
             */
            $firstName = trim(
                (string) ($shippingAddress->first_name ?? '')
            );

            $lastName = trim(
                (string) ($shippingAddress->last_name ?? '')
            );

            $fullName = trim(
                $firstName . ' ' . $lastName
            );

            $address = trim(
                (string) (
                    $shippingAddress->address1
                    ?? $shippingAddress->address
                    ?? ''
                )
            );

            $postalCode = trim(
                (string) (
                    $shippingAddress->postcode
                    ?? ''
                )
            );

            $city = trim(
                (string) (
                    $shippingAddress->city
                    ?? ''
                )
            );

            $province = trim(
                (string) (
                    $shippingAddress->state
                    ?? ''
                )
            );

            $phone = $this->normalizeMobile(
                (string) (
                    $shippingAddress->phone
                    ?? ''
                )
            );

            /*
             * TorobPay documentation requires these fields.
             */
            $requiredFields = [
                'address' => $address,
                'postalCode' => $postalCode,
                'name_full_customer' => $fullName,
                'city' => $city,
                'province' => $province,
                'number_phone_registration' => $phone,
            ];

            foreach ($requiredFields as $field => $value) {
                if ($value === '') {
                    return $this->checkoutError(
                        'اطلاعات ' . $field . ' برای پرداخت ترب‌پی کامل نیست.'
                    );
                }
            }

            $callbackUrl = route(
                'torobpay.payment.callback'
            );

            /*
             * Create payment request exactly according to
             * the TorobPay CPG documentation.
             */
            $payload = [
                'amount' => $amount,

                'paymentMethodTypeDto' => 'ONLINE_CREDIT',

                'returnURL' => $callbackUrl,

                'transactionId' => $transactionId,

                'cartList' => $cartList,

                'address' => $address,

                'postalCode' => $postalCode,

                'name_full_customer' => $fullName,

                'city' => $city,

                'province' => $province,

                'number_phone_registration' => $phone,
            ];

            /*
             * The documented optional customer mobile field.
             */
            if ($phone !== '') {
                $payload['mobile'] = $phone;
            }

            Log::info('TorobPay payment request.', [
                'transaction_id' => $transactionId,
                'cart_id' => $cart->id,
                'amount' => $amount,
            ]);

            $response =
                $this->torobPayService->createPayment(
                    $payload
                );

            $paymentData =
                $response['response'] ?? [];

            $paymentToken =
                $paymentData['paymentToken'] ?? null;

            $paymentPageUrl =
                $paymentData['paymentPageUrl'] ?? null;

            if (
                ! $paymentToken
                || ! $paymentPageUrl
            ) {
                return $this->checkoutError(
                    'لینک پرداخت ترب‌پی دریافت نشد.'
                );
            }

            /*
             * Save local transaction.
             */
            $transaction =
                $this->torobPayRepository->create([
                    'code' => $response['code'] ?? null,

                    'message' => $response['message'] ?? null,

                    'amount' => $amount,

                    'token' => $paymentToken,

                    'transaction_id' => $transactionId,

                    'status' => 'pending',

                    'request_data' => $payload,

                    'response_data' => $response,
                ]);

            /*
             * Store transaction ID in session only as a secondary
             * fallback. The official callback contains transactionId.
             */
            session([
                'torobpay_transaction_id' => $transaction->id,
            ]);

            return redirect()->away(
                $paymentPageUrl
            );
        } catch (\Throwable $e) {
            Log::error(
                'TorobPay payment redirect failed.',
                [
                    'message' => $e->getMessage(),
                ]
            );

            return $this->checkoutError(
                $e->getMessage()
                ?: 'خطا در اتصال به ترب‌پی.'
            );
        }
    }

    /**
     * Handle TorobPay callback.
     *
     * TorobPay sends:
     * transactionId
     * state
     * amount
     *
     * using POST application/x-www-form-urlencoded.
     */
    public function callback(Request $request)
    {
        try {
            $transactionId = trim(
                (string) $request->input('transactionId')
            );

            $state = strtoupper(
                trim(
                    (string) $request->input('state')
                )
            );

            $callbackAmount = $request->input('amount');

            if ($transactionId === '') {
                return $this->checkoutError(
                    'شناسه تراکنش ترب‌پی دریافت نشد.'
                );
            }

            $transaction =
                $this->torobPayRepository
                    ->findOneWhere([
                        'transaction_id' => $transactionId,
                    ]);

            if (! $transaction) {
                Log::warning(
                    'TorobPay transaction not found.',
                    [
                        'transaction_id' => $transactionId,
                    ]
                );

                return $this->checkoutError(
                    'تراکنش ترب‌پی پیدا نشد.'
                );
            }

            /*
             * Ignore duplicate callbacks.
             */
            if ($transaction->status === 'success') {
                return redirect()->route(
                    'shop.checkout.onepage.success'
                );
            }

            if ($state !== 'OK') {
                $this->torobPayRepository->update(
                    [
                        'status' => 'failed',

                        'message' =>
                            'TorobPay payment failed.',

                        'response_data' => array_merge(
                            is_array($transaction->response_data)
                                ? $transaction->response_data
                                : [],
                            [
                                'callback' =>
                                    $request->all(),
                            ]
                        ),
                    ],
                    $transaction->id
                );

                return $this->checkoutError(
                    'پرداخت ترب‌پی ناموفق بود.'
                );
            }

            /*
             * Verify using paymentToken.
             */
            $paymentToken =
                (string) $transaction->token;

            if ($paymentToken === '') {
                throw new \RuntimeException(
                    'Payment Token ترب‌پی پیدا نشد.'
                );
            }

            $verifyResponse =
                $this->torobPayService->verifyPayment(
                    $paymentToken
                );

            /*
             * Verify local amount against the callback amount
             * when TorobPay has provided one.
             */
            if (
                $callbackAmount !== null
                && $callbackAmount !== ''
                && (int) $callbackAmount !==
                    (int) $transaction->amount
            ) {
                $this->torobPayService->revertPayment(
                    $paymentToken
                );

                $this->torobPayRepository->update(
                    [
                        'status' => 'failed',

                        'message' =>
                            'Payment amount mismatch.',

                        'response_data' => array_merge(
                            is_array($transaction->response_data)
                                ? $transaction->response_data
                                : [],
                            [
                                'callback' =>
                                    $request->all(),
                                'verify' =>
                                    $verifyResponse,
                            ]
                        ),
                    ],
                    $transaction->id
                );

                return $this->checkoutError(
                    'مبلغ پرداخت با مبلغ سفارش مطابقت ندارد.'
                );
            }

            /*
             * Create Bagisto order after successful verification.
             */
            $cart = Cart::getCart();

            if (! $cart) {
                throw new \RuntimeException(
                    'سبد خرید پس از بازگشت از ترب‌پی پیدا نشد.'
                );
            }

            $orderData =
                (new OrderResource($cart))
                    ->jsonSerialize();

            $order =
                $this->orderRepository->create(
                    $orderData
                );

            /*
             * TorobPay requires settle after verify.
             */
            $settleResponse =
                $this->torobPayService->settlePayment(
                    $paymentToken
                );

            $verifyData =
                $verifyResponse['response']
                ?? [];

            $referenceId =
                $verifyData['transactionId']
                ?? $transactionId;

            $responseData =
                is_array($transaction->response_data)
                    ? $transaction->response_data
                    : [];

            $responseData['callback'] =
                $request->all();

            $responseData['verify'] =
                $verifyResponse;

            $responseData['settle'] =
                $settleResponse;

            /*
             * Update local transaction.
             */
            $this->torobPayRepository->update(
                [
                    'order_id' => $order->id,

                    'reference_id' => $referenceId,

                    'status' => 'success',

                    'message' =>
                        'Payment completed successfully.',

                    'response_data' => $responseData,
                ],
                $transaction->id
            );

            /*
             * Mark order as processing.
             */
            $this->orderRepository->update(
                [
                    'status' => 'processing',
                ],
                $order->id
            );

            /*
             * Create invoice.
             */
            if ($order->canInvoice()) {
                $invoiceData = [
                    'order_id' => $order->id,
                    'invoice' => [
                        'items' => [],
                    ],
                ];

                foreach ($order->items as $item) {
                    $invoiceData['invoice']['items'][
                        $item->id
                    ] = $item->qty_to_invoice;
                }

                $this->invoiceRepository->create(
                    $invoiceData
                );
            }

            /*
             * Deactivate cart after the order has been created.
             */
            Cart::deActivateCart();

            session()->forget(
                'torobpay_transaction_id'
            );

            session()->put(
                'order_id',
                $order->id
            );

            return redirect()->route(
                'shop.checkout.onepage.success'
            );
        } catch (\Throwable $e) {
            Log::error(
                'TorobPay callback failed.',
                [
                    'message' => $e->getMessage(),
                    'request' => $request->all(),
                ]
            );

            return $this->checkoutError(
                'پرداخت ترب‌پی ناموفق بود.'
            );
        }
    }

    /**
     * Convert configured store currency to Rial.
     */
    protected function toRial(
        float $amount,
        string $currency
    ): int {
        $amount = (int) round($amount);

        return $currency === 'T'
            ? $amount * 10
            : $amount;
    }

    /**
     * Normalize Iranian mobile number.
     */
    protected function normalizeMobile(
        string $mobile
    ): string {
        $mobile = trim($mobile);

        $mobile = str_replace(
            [' ', '-', '(', ')'],
            '',
            $mobile
        );

        $mobile = strtr(
            $mobile,
            [
                '۰' => '0',
                '۱' => '1',
                '۲' => '2',
                '۳' => '3',
                '۴' => '4',
                '۵' => '5',
                '۶' => '6',
                '۷' => '7',
                '۸' => '8',
                '۹' => '9',

                '٠' => '0',
                '١' => '1',
                '٢' => '2',
                '٣' => '3',
                '٤' => '4',
                '٥' => '5',
                '٦' => '6',
                '٧' => '7',
                '٨' => '8',
                '٩' => '9',
            ]
        );

        if (str_starts_with($mobile, '+98')) {
            $mobile = '0' . substr($mobile, 3);
        } elseif (str_starts_with($mobile, '98')) {
            $mobile = '0' . substr($mobile, 2);
        }

        return $mobile;
    }

    /**
     * Return to checkout with an error.
     */
    protected function checkoutError(
        string $message
    ) {
        return redirect()
            ->route('shop.checkout.onepage.index')
            ->with('error', $message);
    }
}